services:
  psql:
    container_name: database
    image: postgres:15.1
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d ${DB_NAME} -U ${DB_USERNAME}"]
      interval: 3s
      timeout: 10s
      retries: 5
    ports:
      - "${DB_PORT}:${DB_PORT}"
    volumes:
      - psql_volume:/var/lib/postgresql/data
  city-tags-api:
    container_name: api
    image: city-tags-api:latest
    build:
      context: .
      dockerfile: Dockerfile.api
    entrypoint: ./main
    depends_on:
      psql:
        condition: service_healthy
    environment:
      ENV: ${ENV}
      SERVER_PORT: ${SERVER_PORT}
      DB_HOST: psql
      DB_PORT: ${DB_PORT}
      DB_NAME: ${DB_NAME}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
    healthcheck:
      test: ["CMD-SHELL", "curl --fail http://localhost:8080/ping || exit 1"]
      interval: 1s
      timeout: 10s
      retries: 10
    ports:
      - "${SERVER_PORT}:${SERVER_PORT}"
  integration-tests:
    container_name: integration-tests
    image: integration-tests:latest
    build:
      context: .
      dockerfile: Dockerfile.tests
    depends_on:
      psql:
        condition: service_healthy
      city-tags-api:
        condition: service_healthy
    entrypoint: tail -f /dev/null

volumes:
  psql_volume:
