services:
  psql:
    image: postgres:15.1
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d ${DB_NAME} -U ${DB_USERNAME}"]
      interval: 3s
      timeout: 10s
      retries: 5
    ports:
      - "${DB_PORT}:${DB_PORT}"
    volumes:
      - psql_volume:/var/lib/postgresql/data
  city-tags-api:
    image: city-tags-api-test:latest
    build: .
    entrypoint: ./main
    depends_on:
      psql:
        condition: service_healthy
    environment:
      ENV: ${ENV}
      SERVER_PORT: ${SERVER_PORT}
      DB_HOST: psql
      DB_PORT: ${DB_PORT}
      DB_NAME: ${DB_NAME}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
    ports:
      - "${SERVER_PORT}:${SERVER_PORT}"

volumes:
  psql_volume:
